---
language: python

services:
  - docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    # - MOLECULE_DISTRO: fedora27
    # - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    # - MOLECULE_DISTRO: debian9

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y net-tools
install:
  - pip install molecule docker-py

script:
  - molecule --version
  - ansible --version
  - ./.travis-ci.d/wrap-test.sh
